var searchData=
[
  ['test_5fcheck_5fborders_2ecpp',['test_check_borders.cpp',['../test__check__borders_8cpp.html',1,'']]],
  ['test_5fread_5fwrite_2ecpp',['test_read_write.cpp',['../test__read__write_8cpp.html',1,'']]],
  ['tilebordervertices',['TileBorderVertices',['../classTileBorderVertices.html',1,'']]],
  ['tileeastvertices',['tileEastVertices',['../structBordersData.html#a6a20e32c0da52b91d94a5cedbc3fd52f',1,'BordersData']]],
  ['tilenorthvertices',['tileNorthVertices',['../structBordersData.html#a1065903f2f5e8f2f0a311658c26363c0',1,'BordersData']]],
  ['tilesouthvertices',['tileSouthVertices',['../structBordersData.html#a454b580cd2173b1ce0579b99e9c5f28a',1,'BordersData']]],
  ['tilewestvertices',['tileWestVertices',['../structBordersData.html#a2bcdd2959a84f4c26358a19d690bda8c',1,'BordersData']]],
  ['tincreation',['TinCreation',['../namespaceTinCreation.html',1,'']]],
  ['tincreationdelaunaystrategy',['TinCreationDelaunayStrategy',['../classTinCreation_1_1TinCreationDelaunayStrategy.html',1,'TinCreation']]],
  ['tincreationgreedyinsertionstrategy',['TinCreationGreedyInsertionStrategy',['../classTinCreation_1_1TinCreationGreedyInsertionStrategy.html',1,'TinCreation::TinCreationGreedyInsertionStrategy'],['../classTinCreation_1_1TinCreationGreedyInsertionStrategy.html#aa2d6662fd399ba05025535bf122cff1d',1,'TinCreation::TinCreationGreedyInsertionStrategy::TinCreationGreedyInsertionStrategy(double rootApproxTolerance, int initGridSamples=-1, int errorType=ErrorHeight)'],['../classTinCreation_1_1TinCreationGreedyInsertionStrategy.html#a337b21a0f97924eea53d97ef3b9d3d20',1,'TinCreation::TinCreationGreedyInsertionStrategy::TinCreationGreedyInsertionStrategy(const std::vector&lt; FT &gt; &amp;approxTolPerZoom, int initGridSamples=-1, int errorType=ErrorHeight)']]],
  ['tincreationremeshingstrategy',['TinCreationRemeshingStrategy',['../classTinCreation_1_1TinCreationRemeshingStrategy.html',1,'TinCreation']]],
  ['tincreationsimplificationlindstromturkstrategy',['TinCreationSimplificationLindstromTurkStrategy',['../classTinCreation_1_1TinCreationSimplificationLindstromTurkStrategy.html',1,'TinCreation::TinCreationSimplificationLindstromTurkStrategy'],['../classTinCreation_1_1TinCreationSimplificationLindstromTurkStrategy.html#a4b24a58df01e9b55029f55fb373f66cb',1,'TinCreation::TinCreationSimplificationLindstromTurkStrategy::TinCreationSimplificationLindstromTurkStrategy(int stopEdgesCount, double weightVolume=0.5, double weightBoundary=0.5, double weightShape=1e-10)'],['../classTinCreation_1_1TinCreationSimplificationLindstromTurkStrategy.html#a1810221de6346314739a90f7fd7f964a',1,'TinCreation::TinCreationSimplificationLindstromTurkStrategy::TinCreationSimplificationLindstromTurkStrategy(std::vector&lt; int &gt; stopEdgesCountPerZoom, double weightVolume=0.5, double weightBoundary=0.5, double weightShape=1e-10)']]],
  ['tincreationsimplificationpointset',['TinCreationSimplificationPointSet',['../classTinCreation_1_1TinCreationSimplificationPointSet.html',1,'TinCreation::TinCreationSimplificationPointSet'],['../classTinCreation_1_1TinCreationSimplificationPointSet.html#adf88f46c81c13e1c0eaa93c98d73d4b2',1,'TinCreation::TinCreationSimplificationPointSet::TinCreationSimplificationPointSet(double borderSimplificationMaxDistance, double borderSimplificationMaxLengthPercent, unsigned int minFeaturePolylineSize)'],['../classTinCreation_1_1TinCreationSimplificationPointSet.html#aea5a473b64a275795ba459718ad97241',1,'TinCreation::TinCreationSimplificationPointSet::TinCreationSimplificationPointSet(const std::vector&lt; double &gt; &amp;borderSimplificationMaxDistance, const std::vector&lt; double &gt; &amp;borderSimplificationMaxLengthPercent, unsigned int minFeaturePolylineSize)']]],
  ['tincreationsimplificationpointsetgrid',['TinCreationSimplificationPointSetGrid',['../classTinCreation_1_1TinCreationSimplificationPointSetGrid.html',1,'TinCreation::TinCreationSimplificationPointSetGrid'],['../classTinCreation_1_1TinCreationSimplificationPointSetGrid.html#a72faa3aa0ec61103545b5bed2485ddf4',1,'TinCreation::TinCreationSimplificationPointSetGrid::TinCreationSimplificationPointSetGrid(double borderSimplificationMaxDistance, double borderSimplificationMaxLength, unsigned int minFeaturePolylineSize, double cellSize)'],['../classTinCreation_1_1TinCreationSimplificationPointSetGrid.html#a9ff4aba13c5c5180daa54fcf1e4df602',1,'TinCreation::TinCreationSimplificationPointSetGrid::TinCreationSimplificationPointSetGrid(const std::vector&lt; double &gt; &amp;borderSimplificationMaxDistancePerZoom, const std::vector&lt; double &gt; &amp;borderSimplificationMaxLengthPerZoom, unsigned int minFeaturePolylineSize, const std::vector&lt; double &gt; &amp;cellSizePerZoom)']]],
  ['tincreationsimplificationpointsethierarchy',['TinCreationSimplificationPointSetHierarchy',['../classTinCreation_1_1TinCreationSimplificationPointSetHierarchy.html',1,'TinCreation::TinCreationSimplificationPointSetHierarchy'],['../classTinCreation_1_1TinCreationSimplificationPointSetHierarchy.html#a857169ab9ac603508d6d57c31acedd55',1,'TinCreation::TinCreationSimplificationPointSetHierarchy::TinCreationSimplificationPointSetHierarchy(double borderSimplificationMaxDistance, double borderSimplificationMaxLength, unsigned int minFeaturePolylineSize, unsigned int maxClusterSize, double maxSurfaceVariance)'],['../classTinCreation_1_1TinCreationSimplificationPointSetHierarchy.html#a5d65ff5a540dc090b9313f1c17dd355e',1,'TinCreation::TinCreationSimplificationPointSetHierarchy::TinCreationSimplificationPointSetHierarchy(const std::vector&lt; double &gt; &amp;borderSimplificationMaxDistancePerZoom, const std::vector&lt; double &gt; &amp;borderSimplificationMaxLengthPerZoom, unsigned int minFeaturePolylineSize, const std::vector&lt; unsigned int &gt; &amp;maxClusterSizePerZoom, const std::vector&lt; double &gt; &amp;maxSurfaceVariancePerZoom)']]],
  ['tincreationsimplificationpointsetrandom',['TinCreationSimplificationPointSetRandom',['../classTinCreation_1_1TinCreationSimplificationPointSetRandom.html',1,'TinCreation::TinCreationSimplificationPointSetRandom'],['../classTinCreation_1_1TinCreationSimplificationPointSetRandom.html#ab21b34d95e3b02b8fbec9507128307e4',1,'TinCreation::TinCreationSimplificationPointSetRandom::TinCreationSimplificationPointSetRandom(double borderSimplificationMaxDistance, double borderSimplificationMaxLength, unsigned int minFeaturePolylineSize, double removePercentage)'],['../classTinCreation_1_1TinCreationSimplificationPointSetRandom.html#a4971b507d10e2b67fba64a2603914638',1,'TinCreation::TinCreationSimplificationPointSetRandom::TinCreationSimplificationPointSetRandom(std::vector&lt; double &gt; borderSimplificationMaxDistancePerZoom, std::vector&lt; double &gt; borderSimplificationMaxLengthPerZoom, unsigned int minFeaturePolylineSize, std::vector&lt; double &gt; removePercentagePerZoom)']]],
  ['tincreationsimplificationpointsetwlop',['TinCreationSimplificationPointSetWLOP',['../classTinCreation_1_1TinCreationSimplificationPointSetWLOP.html',1,'TinCreation::TinCreationSimplificationPointSetWLOP'],['../classTinCreation_1_1TinCreationSimplificationPointSetWLOP.html#a537d0f62712d956d3c322eeb55949cc6',1,'TinCreation::TinCreationSimplificationPointSetWLOP::TinCreationSimplificationPointSetWLOP(double borderSimplificationMaxDistance, double borderSimplificationMaxLength, unsigned int minFeaturePolylineSize, double retainPercentage, double radius, unsigned int iterNumber=35)'],['../classTinCreation_1_1TinCreationSimplificationPointSetWLOP.html#a51868de81acab8ab3bc337018918fb41',1,'TinCreation::TinCreationSimplificationPointSetWLOP::TinCreationSimplificationPointSetWLOP(std::vector&lt; double &gt; borderSimplificationMaxDistancePerZoom, std::vector&lt; double &gt; borderSimplificationMaxLengthPerZoom, unsigned int minFeaturePolylineSize, std::vector&lt; double &gt; retainPercentagePerZoom, std::vector&lt; double &gt; radiusPerZoom, unsigned int iterNumber=35)']]],
  ['tincreationstrategy',['TinCreationStrategy',['../classTinCreation_1_1TinCreationStrategy.html',1,'TinCreation::TinCreationStrategy'],['../classTinCreation_1_1TinCreationStrategy.html#a5adfda2a9e362ab2f48342005cedf4c7',1,'TinCreation::TinCreationStrategy::TinCreationStrategy()']]],
  ['tincreator',['TinCreator',['../classTinCreation_1_1TinCreator.html',1,'TinCreation::TinCreator'],['../classTinCreation_1_1TinCreator.html#a788e70a68947c9b5173f57be67efa2d3',1,'TinCreation::TinCreator::TinCreator()']]],
  ['trianglecount',['triangleCount',['../structQuantizedMesh_1_1IndexData.html#a94635dea8dd214d2e8d1d5a3366c9613',1,'QuantizedMesh::IndexData']]]
];
